version: '3.8'

services:
    phpmyadmin:
        image: phpmyadmin:5.1
        ports:
            -   8071:80
        environment:
            PMA_HOST: db_server
            PMA_USER: root
            PMA_PASSWORD: root

    db_server:
        image: mariadb:10.4
        command: --innodb-use-native-aio=0
        volumes:
            - db_server:/var/lib/mysql
        ports:
            - 3308:3306
        environment:
            MYSQL_ROOT_PASSWORD: root

volumes:
    db_server:
